---- Syntax
/*
WITH [RECURSIVE] CTE_name as
    (
    SELECT query (Base Query)
    UNION [ALL]
    SELECT query (Recursive query using CTE_name [with a termination condition])
    )
SELECT * FROM CTE_name;
*/

--- Q1: Display number from 1 to 10 without using any in built functions.

WITH RECURSIVE NUMBERS AS
    (
    SELECT 1 AS N   --  First iteration.
    UNION ALL
    SELECT N + 1 FROM NUMBERS WHERE N < 10
    )
SELECT * FROM NUMBERS;

--- Q2: Find the hierarchy of employees under a given manager 'Asha'.

CREATE TABLE EMP_DETAILS
(
ID INT,
NAME STRING,
MANAGER_ID INT,
SALARY NUMBER,
DESIGNATION STRING
);

INSERT INTO EMP_DETAILS VALUES
(1,'Shripadh',NULL,10000,'CEO'),
(2,'Satya',5,1400,'Software Engineer'),
(3,'Jia',5,500,'Data Analyst'),
(4,'David',5,1800,'Data Scientist'),
(5,'Michael',7,3000,'Manager'),
(6,'Arvind',7,2400,'Architect'),
(7,'Asha',1,4200,'CTO'),
(8,'Maryam',1,3500,'Manager'),
(9,'Reshma',8,2000,'Business Analyst'),
(10,'Akshay',8,2500,'Java Developer');

SELECT * FROM EMP_DETAILS;
--- STEP:1
WITH RECURSIVE EMP_HIERARCHY AS
    (
    SELECT * FROM EMP_DETAILS WHERE NAME = 'Asha'
    )
SELECT * FROM EMP_HIERARCHY;

--- STEP:2 
WITH RECURSIVE EMP_HIERARCHY AS
    (
    SELECT * FROM EMP_DETAILS WHERE NAME = 'Asha'
    UNION ALL
    SELECT ED.ID AS ID, ED.NAME AS NAME, ED.MANAGER_ID AS MANAGER_ID, ED.SALARY AS SALARY, ED.DESIGNATION AS DESIGNATION
    FROM EMP_HIERARCHY EH
    INNER JOIN EMP_DETAILS ED ON EH.ID = ED.MANAGER_ID
    )
SELECT * FROM EMP_HIERARCHY;

---- Lets understand at which iteration which records fetched

WITH RECURSIVE EMP_HIERARCHY AS
    (
    SELECT ID,NAME,MANAGER_ID, DESIGNATION, 1 AS ITERATION_NUMBER FROM EMP_DETAILS WHERE NAME = 'Asha'
    UNION ALL
    SELECT ED.ID AS ID, ED.NAME AS NAME, ED.MANAGER_ID AS MANAGER_ID, ED.DESIGNATION AS DESIGNATION, ITERATION_NUMBER + 1 AS ITERATION_NUMBER
    FROM EMP_HIERARCHY EH
    INNER JOIN EMP_DETAILS ED ON EH.ID = ED.MANAGER_ID
    )
SELECT * FROM EMP_HIERARCHY;

WITH RECURSIVE EMP_HIERARCHY AS
    (
    SELECT ID,NAME,MANAGER_ID, DESIGNATION, 1 AS ITERATION_NUMBER FROM EMP_DETAILS WHERE NAME = 'Asha'
    UNION ALL
    SELECT ED.ID AS ID, ED.NAME AS NAME, ED.MANAGER_ID AS MANAGER_ID, ED.DESIGNATION AS DESIGNATION, ITERATION_NUMBER + 1 AS ITERATION_NUMBER
    FROM EMP_HIERARCHY EH
    INNER JOIN EMP_DETAILS ED ON EH.ID = ED.MANAGER_ID
    )
SELECT EH.ID AS ID, EH.NAME AS NAME, EH.MANAGER_ID AS MANAGER_ID, ED.NAME AS MANAGER_NAME, EH.ITERATION_NUMBER AS ITERATION_NUMBER FROM EMP_HIERARCHY EH
INNER JOIN EMP_DETAILS ED ON
EH.MANAGER_ID = ED.ID;


--- Q3: Find the hierarchy of the managers for a given employee.

WITH RECURSIVE EMP_HIERARCHY AS
    (
    SELECT ID,NAME,MANAGER_ID, DESIGNATION, 1 AS ITERATION_NUMBER FROM EMP_DETAILS WHERE NAME = 'David'
    UNION ALL
    SELECT ED.ID AS ID, ED.NAME AS NAME, ED.MANAGER_ID AS MANAGER_ID, ED.DESIGNATION AS DESIGNATION, ITERATION_NUMBER + 1 AS ITERATION_NUMBER
    FROM EMP_HIERARCHY EH
    INNER JOIN EMP_DETAILS ED ON EH.MANAGER_ID = ED.ID
    )
SELECT EH.ID AS ID, EH.NAME AS NAME, EH.MANAGER_ID AS MANAGER_ID, ED.NAME AS MANAGER_NAME, EH.ITERATION_NUMBER AS ITERATION_NUMBER FROM EMP_HIERARCHY EH
INNER JOIN EMP_DETAILS ED ON
EH.MANAGER_ID = ED.ID;
